modLoader = "kotlinforforge"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "?"

[[mods]]
modId = "yummy"
version = "${version}"
displayName = "Yummy Mod"
authors = "YummyLoop"
description = '''
This is an yummy mod!
'''
#logoFile = ""

[[dependencies.yummy]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yummy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yummy]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"